"""adds foreign key to Review

Revision ID: bfd83741ad3d
Revises: 9e0bd1db7ea0
Create Date: 2025-02-23 08:07:06.414680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd83741ad3d'
down_revision = '9e0bd1db7ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reviews_employee', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_employee', type_='foreignkey')
        batch_op.drop_column('employee_id')
    # ### end Alembic commands ###
